definitions:
  model.Task:
    properties:
      category_id:
        description: Внешний ключ для связи с TaskCategory
        type: integer
      created_at:
        type: string
      deleted_at:
        type: string
      description:
        type: string
      id:
        type: integer
      is_completed:
        type: boolean
      taskCategory:
        allOf:
        - $ref: '#/definitions/model.TaskCategory'
        description: Связь с TaskCategory
      title:
        type: string
      updated_at:
        type: string
    type: object
  model.TaskCategory:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      updated_at:
        type: string
    type: object
info:
  contact: {}
paths:
  /categories:
    get:
      consumes:
      - application/json
      description: Get details of all task categories
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.TaskCategory'
            type: array
      summary: Get list of task categories
      tags:
      - categories
    post:
      consumes:
      - application/json
      description: Add a new task category
      parameters:
      - description: Task Category to add
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/model.TaskCategory'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.TaskCategory'
      summary: Create a new task category
      tags:
      - categories
  /categories/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a task category by ID
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: Not found
          schema:
            type: object
      summary: Delete a task category
      tags:
      - categories
    get:
      consumes:
      - application/json
      description: Get details of a task category by ID
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.TaskCategory'
        "404":
          description: Not found
          schema:
            type: object
      summary: Get a task category
      tags:
      - categories
    put:
      consumes:
      - application/json
      description: Update task category details by ID
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      - description: Task Category body to update
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/model.TaskCategory'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.TaskCategory'
        "400":
          description: Bad Request
          schema:
            type: object
        "404":
          description: Not found
          schema:
            type: object
      summary: Update a task category
      tags:
      - categories
  /tasks:
    get:
      consumes:
      - application/json
      description: Get details of all tasks
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Task'
            type: array
      summary: Get list of tasks
      tags:
      - tasks
    post:
      consumes:
      - application/json
      description: add by json task
      parameters:
      - description: Add Task
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/model.Task'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Task'
      summary: Create a new task
      tags:
      - tasks
  /tasks/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a task by ID
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: Not found
          schema:
            type: object
      summary: Delete a task
      tags:
      - tasks
    get:
      consumes:
      - application/json
      description: Get details of a task by ID
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Task'
        "404":
          description: Not found
          schema:
            type: object
      summary: Get a task
      tags:
      - tasks
    put:
      consumes:
      - application/json
      description: Update task details by ID
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: integer
      - description: Task body to update
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/model.Task'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Task'
        "400":
          description: Bad Request
          schema:
            type: object
        "404":
          description: Not found
          schema:
            type: object
      summary: Update a task
      tags:
      - tasks
swagger: "2.0"
